import Head from 'next/head'

import GlobalStyles from '~/styles/global'

import type { AppProps } from 'next/app'

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>
          React Avançado - Crie aplicações reais com NextJS, GraphQL e mais.
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="/img/icon-512.png" />
        <link rel="apple-touch-icon" href="/img/icon-512.png" />
      </Head>
      <GlobalStyles />
      <Component {...pageProps} />
    </>
  )
}
