import Head from 'next/head'
import Image from 'next/image'
import logo from '../../public/logo.png'
import styles from '../../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Boilerplate NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.logo}>
        <Image src={logo} alt="Logo da tamirfaria.dev" />
      </div>
    </>
  )
}
